const hubspot = {
  portalId: 9494835,
  userMessage: { message: "noesrafa@gmail.com", quickReply: null },
  parsedResult: null,
  bot: {
    nickname: "PRY-CX AI",
    conversationChannelType: "WEB",
    chatflowId: 44242481,
  },
  module: {
    botNickname: "PRY-CX AI",
    fallbackNextModuleNickname: null,
    failureNextModuleNickname: null,
    moduleType: "WEBHOOK",
    nickname: "Send message to openai",
    prompt: null,
    promptHtml: null,
    config: {
      id: 764547,
      timeout: 3000,
      customPayload: null,
      expectingResponse: true,
    },
  },
  session: {
    vid: 29822800565,
    conversationId: 7353134123,
    botNickname: "PRY-CX AI",
    currentModuleNickname: "Send message to openai",
    sessionStartedAt: 1718299462785,
    lastInteractionAt: 1718299471799,
    state: "ACTIVE",
    customState: {},
    responseExpected: false,
    parsedResponses: { "Get email": [Object], "Welcome message": [Object] },
    properties: { CONTACT: [Object], CONVERSATION: [Object] },
  },
  customPayload: null,
};
